#code to plot and analyze weight at age output from individual based model of sardine generated by J. FIechter
#waa data is plotted and then turned into laa
#VBGM fit to the laa output from the IBM to estimate parameters in the historical and projections period
#the change in growth parameters is then applied to the base OM growth parameters
#author: D. Tommasi

library(ggplot2)
library(tidyverse)
library(FSA)
library(car)
library(nlstools)
library(plotrix)
library(nlme)
library(nlraa)

#when you clone the MSescenarios repository https://github.com/futureseas/MSEscenarios 
#and open the project, the working directory should automatically be MSEscenarios
# check that's the case
getwd()
#specify path of working directory
wpath <- getwd()

#read weight at age output from IBM - it will take a little bit, it's a large file
wgtsnna=read.csv(paste0(wpath,"/dat/ibmwgtsmat.csv"))

wts.plot<-ggplot(wgtsnna %>% filter(year %in% c(1991:2020, 2071:2100)),aes(x = as.factor(age), y = wgtmd, color=Period)) +
  geom_boxplot(outliers=FALSE)+
  labs(title = "", x = "Age", y = "Weight (g)") +
  scale_color_manual(values = c("1991-2020"="cyan3","2071-2100"="brown2"),
                     labels = c("1991-2020"="Historical","2071-2100"="Climate"))+
  theme_bw()+facet_grid(months~ESM)+theme(legend.title = element_blank())
dev.new(width=5, height=3)
png("Gplot_byesmandseas.png", width = 5, height = 3, units = 'in', res = 300)
wts.plot
dev.off()

#---------------------------figure 5-----------------------------------------------------
wt.plot<-ggplot(wgtsnna %>% filter(year %in% c(1991:2020, 2071:2100)),aes(x = as.factor(age), y = wgtmd, color=Period)) +
  geom_boxplot(outliers=FALSE)+
  labs(title = "", x = "Age", y = "Weight (g)") +
  scale_color_manual(values = c("1991-2020"="cyan3","2071-2100"="brown2"),
                     labels = c("1991-2020"="Historical","2071-2100"="Future\nClimate"))+
  theme_bw()+facet_grid(.~ESM)+theme(legend.title = element_blank())
dev.new(width=5, height=3)
png("Gplot_byesm.png", width = 5, height = 3, units = 'in', res = 300)
wt.plot
dev.off()
#--------------------------------------------------------------------------------------------

#compute differences in mean WAA by age and scenario
waasmry <- wgtsnna %>% group_by(Period, age,ESM)%>%summarise(
  mwaa = mean(wgtmd)
)

#split by historical and future periods
waahist <- waasmry %>% filter(Period=="1991-2020")
waafut <- waasmry %>% filter(Period=="2071-2100")

waafut$rchange <- ((waafut$mwaa-waahist$mwaa)/waahist$mwaa)*100

waafut%>% group_by(ESM)%>%summarize(mrchange=mean(rchange))

#plot with all years
wt.plotall<-ggplot(wgtsnna %>% filter(year %in% c(1991:2100)),aes(x = as.factor(age), y = wgtmd, color=Period)) +
  geom_boxplot(outliers=FALSE)+
  labs(title = "", x = "Age", y = "Weight (g)") +
  #scale_color_manual(values = c("1991-2020"="cyan3","2071-2100"="brown2"))+
  theme_bw()+theme(legend.title = element_blank())
dev.new(width=5, height=3)
png("Gplot_byesm_all.png", width = 5, height = 3, units = 'in', res = 300)
wt.plotall
dev.off()

#generate lengths from weights using the relationship in base OM of Wildermuth et al. 2024
wgtsnna$length<-((wgtsnna$wgtmd/1000)/(7.5242e-6))^(1/3.2332)

#Fit VB model to IBM data
#code modified from https://danstich.github.io/we-r-nycafs/fishStats.html
# Define von Bertalanffy growth function - SS style

# Parameters from Stock Synthesis base OM of Wildermuth et al. 2024
L_at_Amin <- 13.1626 
L_inf <- 25.1617
K <- 0.274765     
age0 <- 0.5 

# Generate ages
ages <- seq(0, 10, by = 0.1)

# Calculate predicted lengths in cm given OM Von Bert
lengths <- L_inf+(L_at_Amin-L_inf)*exp(-K * (ages - age0))

#Generate table to save the LB parameters scaled to the OM for each ESM
LBpars <-data.frame(ESM=c("GFDL","HADL","IPSL"),Linf=rep(NA,3),Lmin=rep(NA,3),K=rep(NA,3))
LBparsh <-data.frame(ESM=c("GFDL","HADL","IPSL"),Linf=rep(NA,3),Lmin=rep(NA,3),K=rep(NA,3))
LBparsp <-data.frame(ESM=c("GFDL","HADL","IPSL"),Linf=rep(NA,3),Lmin=rep(NA,3),K=rep(NA,3))

#specify Von Bertalanffy growth model
vbmod <- length ~ L_inf+(L_at_Amin-L_inf)*exp(-K*(age - 0.5))

#Use base OM as starting values 
starts <- data.frame(L_inf = 25.1617, L_at_Amin = 13.1626, K = 0.274765 )
startsp <- data.frame(L_inf = 25.1617, L_at_Amin = 13.1626)

#function to fit he VBGM to the IBM output for each ESM in the historical and projection periods
#and find the estimated growth parameters in each period

LBparam <-function(esm){
  # Fit the von Bertalanffy growth function using
  # nonlinear least squares (nls) optimization
  #over the historical period
  vbh <- nls(vbmod, data = wgtsnna%>%filter(ESM==esm&year%in%c(1991:2020)), start = starts)
  #summary(vbh)
  #extract the historical parameter estimates
  LBparshv=vbh$m$getPars()
  
  #K is inversely related to Linf, K=E/Linf (Essington et al. 2001)
  #to mantain that relationship in the projection between K and Linf we find
  #E, E = K*L_inf,in the historical and set K as a function of E and Linf in the projection fit
  #so in the projections only L_inf and L_at_Amin are estimated
  
  #find E using the fitted parameters from the historical fit
  E = LBparshv[1]*LBparshv[3]
  
  #define a new VBGM where K is a function of L_inf and E
  vbmodp <- length ~ L_inf+(L_at_Amin-L_inf)*exp(-(E/L_inf) * (age - 0.5))
  #fit the model to the IBm projections
  vbp <- nls(vbmodp, data = wgtsnna%>%filter(ESM==esm&year%in%c(2071:2100)), start = startsp)
  #summary(vbp)
  #extract the projection parameter estimates
  LBparspv=vbp$m$getPars()
  #calculate proportional difference in params
  Linfp= (vbp$m$getPars()[1]-vbh$m$getPars()[1])/vbh$m$getPars()[1]
  LAminP = (vbp$m$getPars()[2]-vbh$m$getPars()[2])/vbh$m$getPars()[2]
  Kp = (E/vbp$m$getPars()[1]-vbh$m$getPars()[3])/(vbh$m$getPars()[3])
  
  #apply the change to the base growth pars to find the climate infomred OM growth parameters
  L_infc = L_inf*Linfp+L_inf
  L_at_Aminc = L_at_Amin*LAminP+L_at_Amin
  Kc = K*Kp+K
  param.dat = c(L_infc,L_at_Aminc,Kc )
  parmat <-data.frame(param.dat=param.dat,histpar=c(LBparshv),projpar=c(LBparspv,E/LBparspv[1]))
  return(parmat)
}

LBpars.gfdl=LBparam(esm="GFDL")
LBpars.hadl=LBparam(esm="HADL")
LBpars.ipsl=LBparam(esm="IPSL")

#calculate the lengths for the IBM data
lengthsci.gfdl <- LBpars.gfdl$projpar[1]+(LBpars.gfdl$projpar[2]-LBpars.gfdl$projpar[1])*exp(-LBpars.gfdl$projpar[3] * (ages - age0))
lengthsci.hadl <- LBpars.hadl$projpar[1]+(LBpars.hadl$projpar[2]-LBpars.hadl$projpar[1])*exp(-LBpars.hadl$projpar[3] * (ages - age0))
lengthsci.ipsl <- LBpars.ipsl$projpar[1]+(LBpars.ipsl$projpar[2]-LBpars.ipsl$projpar[1])*exp(-LBpars.ipsl$projpar[3] * (ages - age0))

lengthsi.gfdl <- LBpars.gfdl$histpar[1]+(LBpars.gfdl$histpar[2]-LBpars.gfdl$histpar[1])*exp(-LBpars.gfdl$histpar[3] * (ages - age0))
lengthsi.hadl <- LBpars.hadl$histpar[1]+(LBpars.hadl$histpar[2]-LBpars.hadl$histpar[1])*exp(-LBpars.hadl$histpar[3] * (ages - age0))
lengthsi.ipsl <- LBpars.ipsl$histpar[1]+(LBpars.ipsl$histpar[2]-LBpars.ipsl$histpar[1])*exp(-LBpars.ipsl$histpar[3] * (ages - age0))

#Combine in one data frame for plotting
vbmati = data.frame(Age=rep(ages,3),Length=c(lengthsi.gfdl,lengthsi.hadl,lengthsi.ipsl),
                    ESM = c(rep("GFDL",101),rep("HADL",101),rep("IPSL",101)))
vbmatic = data.frame(Age=rep(ages,3),Length=c(lengthsci.gfdl,lengthsci.hadl,lengthsci.ipsl),
                     ESM = c(rep("GFDL",101),rep("HADL",101),rep("IPSL",101)))
#extract simulated data for IBM for GFDL and Hadley
dati = wgtsnna%>%filter(ESM=="GFDL"&year %in% c(1991:2020, 2071:2100))
datih = wgtsnna%>%filter(ESM=="HADL"&year %in% c(1991:2020, 2071:2100))
vbgmIBM.gfdl= ggplot() +
  geom_boxplot(data = dati,aes(x = as.factor(age), y = length,, color=Period), outliers=FALSE)+
  geom_line(data = vbmati %>% filter(Age <8&ESM=="GFDL"), aes(x=Age+1,y=Length),color="cyan3", linewidth = 1.2)+
  geom_line(data = vbmatic %>% filter(Age <8&ESM=="GFDL"), aes(x=Age+1,y=Length),color="brown2", linewidth = 1.2)+
  labs(title = "GFDL", x = "Age", y = "Length (cm)") +
  scale_color_manual(values = c("1991-2020"="cyan3","2071-2100"="brown2"),
                     labels = c("1991-2020"="Historical","2071-2100"="Future\nClimate"))+
  theme_bw()+theme(legend.title = element_blank(),legend.position = "inside",
                   legend.position.inside = c(0.75,0.25))
vbgmIBM.had= ggplot() +
  geom_boxplot(data = datih,aes(x = as.factor(age), y = length,, color=Period), outliers=FALSE)+
  geom_line(data = vbmati %>% filter(Age <8&ESM=="HADL"), aes(x=Age+1,y=Length),color="cyan3", linewidth = 1.2)+
  geom_line(data = vbmatic %>% filter(Age <8&ESM=="HADL"), aes(x=Age+1,y=Length),color="brown2", linewidth = 1.2)+
  labs(title = "Hadley", x = "Age", y = "Length (cm)") +
  scale_color_manual(values = c("1991-2020"="cyan3","2071-2100"="brown2"),
                     labels = c("1991-2020"="Historical","2071-2100"="Future\nClimate"))+
  theme_bw()+theme(legend.title = element_blank(),legend.position = "inside",
                   legend.position.inside = c(0.75,0.25))

#Calculate the lengths for the OM VBGM
lengthsc.gfdl <- LBpars.gfdl$param.dat[1]+(LBpars.gfdl$param.dat[2]-LBpars.gfdl$param.dat[1])*exp(-LBpars.gfdl$param.dat[3] * (ages - age0))
lengthsc.hadl <- LBpars.hadl$param.dat[1]+(LBpars.hadl$param.dat[2]-LBpars.hadl$param.dat[1])*exp(-LBpars.hadl$param.dat[3] * (ages - age0))
lengthsc.ipsl <- LBpars.ipsl$param.dat[1]+(LBpars.ipsl$param.dat[2]-LBpars.ipsl$param.dat[1])*exp(-LBpars.ipsl$param.dat[3] * (ages - age0))

#Combine in one data frame for plotting OM VBGM
vbmat = data.frame(Age=rep(ages,4),Length=c(lengths,lengthsc.hadl,lengthsc.gfdl,lengthsc.ipsl),
                   Model = c(rep("Historical",101),rep("HADL",101),rep("GFDL",101),rep("IPSL",101)))
#Plotting historical IBM points over OM growth curve
vb.plotc <- ggplot(vbmat %>%filter(Model !="IPSL"),aes(x = Age, y = Length, color=Model)) +
  geom_line(linewidth = 1.2) +
  scale_color_manual(values = c("Historical"="cyan3","HADL"="brown2",
                                "GFDL"="orange"),
                     labels = c("Historical"="Base OM","HADL"="Future Climate\nHadley",
                                "GFDL"="Future Climate\nGFDL"))+
  scale_x_continuous(breaks = c(0:10))+
  labs(title = "OM Growth Curve", x = "Age", y = "Length (cm)") + theme_bw()

dev.new(width=4, height=4)
png("Gplot_vbc.png", width = 4, height = 4, units = 'in', res = 300)
vb.plotc
dev.off()

#------------------------------------------------------Figure 6-----------------------------------------------------------------
library(gridExtra)
combo.growth <- grid.arrange(arrangeGrob(vbgmIBM.gfdl,vbgmIBM.had,ncol=2),
             vb.plotc,
             nrow=2)
ggsave("Gplot_combo.png",plot = combo.growth, width = 6, height = 8)
